name: Deploy Staging

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NEXT_PUBLIC_FRESHOOD_API_URL: ${{ secrets.NEXT_PUBLIC_FRESHOOD_API_URL }}
      NEXT_PUBLIC_AWS_S3_URL: ${{ secrets.NEXT_PUBLIC_AWS_S3_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📬 Caching
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source:
            "./.next, ./package*.json, ./yarn.lock, ./tsconfig.json, ./public,
            ./next.config.mjs"
          target: "~/deployment"
      - name: Run App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deployment
            npm install
            pm2 restart freshood-fe
